version: '3.8'

services:
  ai-ghaylan:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount volume for persistent storage of results (Windows paths)
      - ./hasil:C:/app/results
      - ./uploads:C:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "powershell", "-Command", "try { Invoke-RestMethod -Uri 'http://localhost:8000/docs' -Method Get -TimeoutSec 10; exit 0 } catch { exit 1 }"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

networks:
  default:
    name: ai-ghaylan-network